[History] Remove travis and make changes to use github actions
dojot/history pull request #108
Opened 2021-04-01 12:37 UTC by marianoleonardo

dojot/dojot#1913

2021-04-05 14:12 UTC, mprevide requested changes
Probably there is a problem when generate documentation because it's empty , check  https://github.com/dojot/history/blob/gh-pages/apiary_test-actions.html

2021-04-14 14:44 UTC, mprevide approved these changes

2021-04-14 14:51 UTC, thiagodpf approved these changes

2021-04-14 15:30 UTC, mprevide approved these changes

2021-04-14 15:50 UTC, merged